# tasks file
---
- name: "install | create (download) directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - "{{ shinycannon_downloads_path }}"
    - "{{ shinycannon_temp_dir_path }}"
  tags:
    - shinycannon-install-download
    - shinycannon-install-download-directory

- name: "install | prepare facts"
  ansible.builtin.set_fact:
    file_extenstion: "{{ shinycannon_download_url | basename | regex_replace('.*\\.(.*)', '\\1') }}"
  tags:
    - shinycannon-install

- name: "install | prepare facts"
  ansible.builtin.set_fact:
    shinycannon_file_destination: "{{ shinycannon_downloads_path }}/shinycannon-{{ shinycannon_version }}.{{ file_extenstion }}" 
  tags:
    - shinycannon-install

- name: "install | shinycannon (download)"
  ansible.builtin.get_url:
    url: "{{ shinycannon_download_url }}"
    dest: "{{ shinycannon_file_destination }}"
    owner: root
    group: root
    mode: 0600
  tags:
    - shinycannon-install
