# tasks file
---

- name: "install | additional"
  ansible.builtin.apt:
    name: "{{ shinycannon_install }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - shinycannon-install-additional

- name: install | shinycannon
  ansible.builtin.apt:
    deb: "{{ shinycannon_file_destination }}"
  tags:
    - shinycannon-install
