# tasks file
---
- name: "include variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - _default.yml
  tags:
    - configuration
    - shinycannon
    - shinycannon-include-variables

- name: Include common tasks
  ansible.builtin.include_tasks: "install_common.yml"
  tags:
    - configuration
    - shinycannon
    - shinycannon-install

- name: Include task for the distribution
  ansible.builtin.include_tasks: "install_{{ ansible_distribution | lower }}.yml"
  tags:
    - configuration
    - shinycannon
    - shinycannon-install
