# tasks file
---
- name: include variables
  include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - _default.yml
  tags:
    - configuration
    - shinycannon
    - shinycannon-include-variables

- include_tasks: "install_{{ ansible_distribution | lower }}.yml"
  tags:
    - configuration
    - shinycannon
    - shinycannon-install
